<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69676d17ecb80',
	'title' => 'block:sizes',
	'fields' => array(
		array(
			'key' => 'field_69676d17f1eb9',
			'label' => 'Заголовок',
			'name' => 'title',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69676d1802723',
					'label' => 'Текст',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_696771715ac67',
					'label' => 'Положение',
					'name' => 'position',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'left' => 'Слева',
						'center' => 'По центру',
					),
					'default_value' => 'center',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'prepend' => '',
					'append' => '',
					'ajax' => 0,
					'placeholder' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'min' => '',
				),
				array(
					'key' => 'field_69676d180388d',
					'label' => 'Тип',
					'name' => 'type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'h1' => 'H1',
						'h2' => 'H2',
					),
					'default_value' => 'h2',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'prepend' => '',
					'append' => '',
					'ajax' => 0,
					'placeholder' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'min' => '',
				),
			),
		),
		array(
			'key' => 'field_60f505dc3bd17',
			'label' => 'Размеры',
			'name' => 'sizes',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_60f5060a3bd18',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Добавить размеры',
			'acfe_repeater_stylised_button' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_60f5060a3bd18',
					'label' => 'Для кого',
					'name' => 'gender',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60f5071e18451',
					'label' => 'Одежда',
					'name' => 'clothes',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_60f851082e824',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Добавить одежду',
					'sub_fields' => array(
						array(
							'key' => 'field_60f851082e824',
							'label' => 'Название категории',
							'name' => 'name',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 3,
							'new_lines' => 'br',
							'acfe_textarea_code' => 0,
						),
						array(
							'key' => 'field_60f5072c18452',
							'label' => 'Иконка',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'uploader' => '',
							'acfe_thumbnail' => 0,
							'upload_folder' => '',
						),
						array(
							'key' => 'field_60f5074b18453',
							'label' => 'Контент',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_wysiwyg_auto_init' => 0,
							'acfe_wysiwyg_height' => 300,
							'acfe_wysiwyg_min_height' => 300,
							'acfe_wysiwyg_max_height' => '',
							'acfe_wysiwyg_valid_elements' => '',
							'acfe_wysiwyg_custom_style' => '',
							'acfe_wysiwyg_disable_wp_style' => 0,
							'acfe_wysiwyg_autoresize' => 0,
							'acfe_wysiwyg_disable_resize' => 0,
							'acfe_wysiwyg_remove_path' => 0,
							'acfe_wysiwyg_menubar' => 0,
							'acfe_wysiwyg_transparent' => 0,
							'acfe_wysiwyg_merge_toolbar' => 0,
							'acfe_wysiwyg_custom_toolbar' => 0,
							'acfe_wysiwyg_toolbar_buttons' => array(
							),
						),
					),
					'acfe_repeater_stylised_button' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1768386971,
));

endif;